### ISSUE TITLE
search a transaction by txid

### ISSUE THREAD

**Issue by LXHLeaner** [paritytech/substrate-api-sidecar#1068]
i can not find the http that about searching a transaction by txid?

**Comment by TarikGul** [comment]
In Substrate you cannot search a tx by its tx id alone. Transaction hashes are not unique like ethereum. You need to poll the chain, and look for the Timepoint (ExtrinsicIndex, and BlockHash) of where the transaction lives, after you emit a transaction.

**Comment by LXHLeaner** [comment]
1.  what is the meaning of "Transaction hashes are not unique like ethereum."?   i only find  a transcation by a txid "0x51eb8e465020750c5a9de629e6d0a011ee2b87b417d108fa211f55d0d6888962"
2. Can you give me a example about "Transaction hashes are not unique" ?

**Comment by jsdw** [comment]
Transaction hashes in Substrate are not necessarily unique (eg unsigned transactions can look identical for instance as they don't have any nonce which changes per transaction from some user). Theoretically two identical transactions with identical hashes could appear in the same block.

In order to identify a specific transaction on the chain then, you can use a combination of the block hash (to get you to a specific block) and the extrinsic index in that block (to identify the specific extrinsic).

If I'm not mistaken, in ethereum all transactions are signed, and so every transaction hash should be different since all transactions from a specific user will have a different nonce value.
