### ISSUE TITLE
/blocks/head returns an unfinalized block when requested with finalized=true

### ISSUE THREAD

**Issue by agilenc** [paritytech/substrate-api-sidecar#1264]
**Description**

When getting `/blocks/head` with a different `finalized` parameter it may occur that we get an unfinalized block back instead of a finalized one when requesting with  `/blocks/head?finalized=true`.

I noticed this happens with `acala, moonbeam, moonriver, efinity, crust, kintsugi`. I couldn't reproduce with relaychains but other parachains may be affected. This seems like a race condition.

**Steps to Reproduce**

Run the following script against SAS
```sh
#!/bin/bash

arr[0]="true"
arr[1]="false"

while true
do
    rand=$[ $RANDOM % 2 ]
    finalizedParam=${arr[$rand]}

    finalized=$(curl -s localhost:8080/blocks/head?finalized=$finalizedParam | jq .finalized)
    
    if [ "$finalized" != "$finalizedParam" ] && [ "$finalizedParam" == "true" ]; then
        echo "Error: requested finalized=$finalizedParam, received block.finalized=$finalized"
        exit 1
    else
        echo "requested finalized=$finalizedParam, received block.finalized=$finalized"
    fi
done
```

**Expected vs. Actual Behavior**

From [the doc](https://paritytech.github.io/substrate-api-sidecar/dist/):

> Boolean representing whether or not to get the finalized head. If it is not set the value defaults to true. When set to false it will attempt to get the newest known block, which may not be finalized.

While when requesting `/blocks/head?finalized=false` we may have a finalized block be returned, the other way around should not happen.

With the provided script you will notice the following output when there is an issue:
```
requested finalized=false, received block.finalized=false
requested finalized=false, received block.finalized=false
requested finalized=true, received block.finalized=true
requested finalized=true, received block.finalized=true
requested finalized=false, received block.finalized=false
Error: requested finalized=true, received block.finalized=false
```

The quickest chain to reproduce the problem for me was `moonbeam`. I used the public endpoint `wss://moonbeam.api.onfinality.io/public-ws`

Tested on SAS `v.14.5.3`

**Comment by TarikGul** [comment]
Great news is I was able to reproduce the issue. Additional great news I was able to find the source of the bug which now just needs to be resolved.

Basic summary: A while back we noticed a lot of users polling the head of a chain, so I ended writing a very simple LRU cache solution that will store a depth of 2 blocks that were previously polled. This caused this issue because a block may have been cached when it was not finalized, then as it becomes finalized it may still be cached and it will return the previous false value. 

Little tricky to fix, but I will have a fix up shortly. Thanks again for the very detailed description, and the simple script.
