### ISSUE TITLE
there is no migration path for noMeta migration

### ISSUE THREAD

**Issue by xlc** [paritytech/substrate-api-sidecar#1274]
When `noMeta` is used, it will complain and ask for migration. But migrate to what?

**Comment by TarikGul** [comment]
This is old legacy code from Pre V14 metadata. It was replaced with the `metadata` query param. Its long overdue for completely removing `noMeta`. Thanks for bringing this up, as its been lost in the queue for a while. I'll get this in tomorrow to finally finish this. 

The expected behavior will be: `metadata` query param takes in two values `scale` or `json` for the format of the metadata, and if the query param is not inputted the field wont be there. 

The controller code can be seen [here](https://github.com/paritytech/substrate-api-sidecar/blob/master/src/controllers/transaction/TransactionMaterialController.ts#L94-L130).
