### ISSUE TITLE
Sidecar's compatibility spec number is ambiguous

### ISSUE THREAD

**Issue by paperfrog1228** [paritytech/substrate-api-sidecar#1400]
**Description**
- Our environment
    - Polkadot main net (v1.1.0)
    - Sidecar (v17.3.1)
   
Occur below error at block number 19550977.

``"{\"code\":500,\"message\":\"Unable to decode storage session.validators:: createType(Vec<Bytes>):: decodeU8aVec: failed at 0x966d74f8027e07b43717b6876d97544f… (index 3/297): Bytes:: Bytes length 1042094949 exceeds 10485760\",\"stack\":\"Error: Unable to decode storage session.validators:: createType(Vec<Bytes>):: decodeU8aVec: failed at 0x966d74f8027e07b43717b6876d97544f… (index 3/297): Bytes:: Bytes length 1042094949 exceeds 10485760\\n    at RpcCore._newType (/usr/src/app/node_modules/@polkadot/rpc-core/cjs/bundle.js:403:19)\\n    at RpcCore._formatStorageData (/usr/src/app/node_modules/@polkadot/rpc-core/cjs/bundle.js:336:21)\\n    at RpcCore._formatOutput (/usr/src/app/node_modules/@polkadot/rpc-core/cjs/bundle.js:301:25)\\n    at RpcCore._formatResult (/usr/src/app/node_modules/@polkadot/rpc-core/cjs/bundle.js:163:20)\\n    at callWithRegistry (/usr/src/app/node_modules/@polkadot/rpc-core/cjs/bundle.js:184:25)\\n    at runMicrotasks (<anonymous>)\\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\",\"level\":\"error\"}\""}``

The offending block has a spec number of 1000001. (https://polkadot.subscan.io/block/19550977)
However, the start time of the problem is ,
when it was upgraded from block 19551000 to 1001002. (https://polkadot.subscan.io/block/19550977)

Here's the question.
1. when the Polkadot runtime network is upgraded to an incompatible specification in the sidecar, do blocks with earlier spec numbers not get traced?
2. v17.3.1 is known to be compatible up to this specification number from the release notes. 
However, the spec number naming in Polkadot has changed recently and it is hard to recognize. How do I read the spec version of a block tested in sidecar? 
https://github.com/paritytech/substrate-api-sidecar/releases/tag/v17.3.1

```
Compatibility
Tested against:
Polkadot v10200
Kusama v10200
Westend v10200
```
I don't know which spec number v10200 refers to.

Thanks in advance.

**Comment by bee344** [comment]
Hi @paperfrog1228 , I think there's a misunderstanding here. The compatibility refers to the client versions against which it was tested, while the `spec_number` refers to the runtime version and is set by the Polkadot Fellowship. You can check the difference and where you can see them in PJS/APPS [here](https://wiki.polkadot.network/docs/learn-runtime-upgrades#runtime-vs-client-versions). So it refers to the node to which you connect sidecar.

Lastly, what's the request you are making that gives you that error? So that we can replicate it an see what's going on.

**Comment by Imod7** [comment]
Hello @paperfrog1228 ,
I will close this issue since it is stale and no feedback is provided. 

Before I close, I am adding some updated answers to your questions : 
1. When the Polkadot runtime network is upgraded, Sidecar should stay backward compatible and be able to decode earlier blocks as well. Also, if a new runtime upgrade introduces breaking changes, we work on integrating them accordingly. The decoding error that you experienced is related to issues like this one https://github.com/paritytech/substrate-api-sidecar/issues/1299 and it is probably a memory issue in Sidecar that we are currently tackling. 

1. In the last Sidecar [releases](https://github.com/paritytech/substrate-api-sidecar/releases) we updated the Compatibility section (thanx @IkerAlus for the suggestion) to state clearly for which node and which runtime release the specific Sidecar version is compatible with. Hope this makes it more clear for you.
