### ISSUE TITLE
v17.5.1 does not show correctly XCM messages

### ISSUE THREAD

**Issue by will-yjn** [paritytech/substrate-api-sidecar#1401]
**Description**
The subscan shows there is an XCM message that deposits 1 KSM to an account: https://kusama.subscan.io/xcm_message/kusama-68882b46f2567e950457e91afcf189c2cbfbf0a1
But querying the sidecar does not return expected result. Related to this issue: https://github.com/paritytech/substrate-api-sidecar/pull/1364

**Steps to Reproduce**
1. Running the docker image v17.5.1 locally.
`docker run --rm -it --read-only --env SAS_SUBSTRATE_URL=wss://kusama-rpc.polkadot.io -p 8080:8080 parity/substrate-api-sidecar:v17.5.1`
2. Send the request to query block 21548602.
`curl -X GET "http://0.0.0.0:8080/blocks/21548602?decodedXcmMsgs=true" -H  "accept: application/json"`

**Expected vs. Actual Behavior**
Expect to see messages in `decodedXcmMsgs`. Instead see empty arrays.
<img width="265" alt="2024-02-26 11 46 53" src="https://github.com/paritytech/substrate-api-sidecar/assets/81351621/03dd5ce3-6cee-472d-8120-8ded55a43295">

**Comment by Imod7** [comment]
Thank you for your question @will-yjn 
The reason you cannot find the upward message is because:

- In Subscan, the link/block you mentioned is where this XCM message was `processed`.
   - block 21548602 - [messagequeue (Processed)](https://kusama.subscan.io/extrinsic/21548602-0?event=21548602-4)
- In Sidecar, we show the block information and the XCM messages that were `included`/`sent` in this block. So to find the XCM message you mentioned you will need to query 2 blocks back (when this XCM message was actually sent) :
   - block 21548600 - [parainherent (enter)](https://kusama.subscan.io/block/21548600) 
   - corresponding endpoint would be `http://0.0.0.0:8080/blocks/21548600?decodedXcmMsgs=true`

Let us know if this answer is sufficient for you so we can close this issue.

**Comment by will-yjn** [comment]
Thank you very much! I still have two questions:
1. Is it always true that XCM will be processed 1 or 2 blocks after it was sent? Not 3 or more blocks?
2. Can sidecar be sure the XCM will succeed when it is sent, since it is processed 2 blocks later?

**Comment by Imod7** [comment]
@will-yjn I am closing this issue as resolved. If you encounter any bugs in the specific or other endpoint, don't hesitate to reopen it or submit a new issue. Thank you for your questions! 💯
