### ISSUE TITLE
Substrate API Sidecar Postman collection has no URLs

### ISSUE THREAD

**Issue by rvalle** [paritytech/substrate-api-sidecar#1440]
**Description**

The Postman collection referred in the Substrate integration [tutorial](https://docs.substrate.io/tutorials/integrate-with-tools/explore-sidecar-endpoints/) lists all Sidecar API methods, but has no URLs populated except for one.

They seem to be missing.

So, the Postman collection cannot be used as intended, to test endpoints.

**Steps to Reproduce**

In the sidecar substrate [tutorial](https://docs.substrate.io/tutorials/integrate-with-tools/explore-sidecar-endpoints/), under the section "Import the API collection", there is a link to the Sidecar [Postman collection](https://documenter.getpostman.com/view/24602305/2s8YsqWaj8#intro).
On this page, if you browse through the endpoints, only the first endpoint "GET account asset balance" has a URL setup. In all the other endpoints it is not populated.

**Expected vs. Actual Behavior**

I expect to be able to explore the API easily, it is impossible with missing endpoints.

[A clear description of what you expected to happen and what actually happened.]

**Comment by rvalle** [comment]
in the meanwhile this resource is better https://paritytech.github.io/substrate-api-sidecar/dist/

**Comment by Imod7** [comment]
@rvalle Thank you for bringing this to our attention. We will update the substrate tutorial link as soon as possible. 

In the meantime, I have generated an unofficial Postman documentation link for you : https://documenter.getpostman.com/view/21393319/2sA3Qs9C9M which contains full up-to-date information for all endpoints with their respective URLs, path parameters, query parameters, etc as shown in our [docs](https://paritytech.github.io/substrate-api-sidecar/dist/).

_Note : baseURL is set to `http://127.0.0.1:8080/` assuming you are running Sidecar locally_

**Comment by rvalle** [comment]
Thanks @Imod7, its nice to easily test around the endpoints.

**Comment by Imod7** [comment]
Once this [PR](https://github.com/substrate-developer-hub/substrate-docs/pull/2155) in substrate-docs is merged, we can close this issue as resolved.

**Comment by Imod7** [comment]
Closing this issue as resolved since : 
- the related PR was merged.
- the link in the substrate docs tutorial was updated.

Keep in mind though that [`docs.substrate.io`](https://docs.substrate.io) will likely be deprecated in the future. So, for the most up-to-date Sidecar documentation, please refer to the official docs at https://paritytech.github.io/substrate-api-sidecar/dist/. Additionally, there are references in the Polkadot wiki : 
- [Node Interaction](https://wiki.polkadot.network/docs/build-node-interaction#substrate-api-sidecar)
- [Integrate Assets](https://wiki.polkadot.network/docs/build-integrate-assets#sidecar)
