### ISSUE TITLE
How many requests/responses are the different endpoints doing?

### ISSUE THREAD

**Issue by Maharacha** [paritytech/substrate-api-sidecar#1499]
Is there information somewhere exactly how many requests and responses each sidecar endpoint is doing to the backend node? Or do you have a suggestion how we could generate such data in an easy way? I need for each endpoint but also for the different combination of parameters.

Thanks!

**Comment by Imod7** [comment]
Hello @Maharacha we recently added additional Prometheus [metrics](https://github.com/paritytech/substrate-api-sidecar?tab=readme-ov-file#prometheus-server) to improve monitoring of Sidecar's performance and we are also in the process of optimizing the code for better efficiency. Here are some relevant PRs : https://github.com/paritytech/substrate-api-sidecar/pull/1483 and https://github.com/paritytech/substrate-api-sidecar/pull/1489 which are linked to the umbrella issue https://github.com/paritytech/substrate-api-sidecar/issues/1361.

From your description though I think you need a more granular approach. If I may ask, what insight you are looking to gain with this type of metric ? And if so, what is the plan to do with this metric/insight ? From our side, we are considering adding metrics like this in the future to identify which endpoints are more `call` heavy. I will need to check with the team and see where it stands in terms of priorities. 

As per your second question, something like this can be implemented by adding a custom metric (e.g. a counter) which increases in every call found in the Controller and Service of each endpoint. If you would like to try it out and open a PR, we would gladly review it and guide you through also. Otherwise, I will get back to you asap with the timeline if and when we can have something like this implemented.

**Comment by Maharacha** [comment]
Thanks for the thorough answer @Imod7 ! It's enough for now to know what options we have to extract that kind of information.

**Comment by Imod7** [comment]
You are welcome! 
Also big kudos to @filvecchiato for all the work he has done on the metrics and performance investigation and changes until now.
