### ISSUE TITLE
Sidecar fails to handle multi block migration events

### ISSUE THREAD

**Issue by ermalkaleci** [paritytech/substrate-api-sidecar#1538]
**Description**
Sidecar fails to handle events generated by pallet-migrations. Sidecar tries to find extrinsic but there're no extrinsic other than inherents during migrations

`SAS_SUBSTRATE_URL=wss://rpc.shiden.astar.network npx @substrate/api-sidecar`
`curl http://localhost:8080/blocks/0xc26eb7b19378e953c80ef9749df2b5ae67a7bdb17b3ad9b9a0ee9c1810438a9f`
"Missing extrinsic 2 in block 0xc26eb7b19378e953c80ef9749df2b5ae67a7bdb17b3ad9b9a0ee9c1810438a9f"

**Comment by Imod7** [comment]
@ermalkaleci Thank you for the issue.

The error you are seeing is triggered [here](https://github.com/paritytech/substrate-api-sidecar/blob/cef2d10ead615b81c11a493310c84411fd45738f/src/services/blocks/BlocksService.ts#L594) in the `BlockService` file which means that the [check](https://github.com/paritytech/substrate-api-sidecar/blob/cef2d10ead615b81c11a493310c84411fd45738f/src/services/blocks/BlocksService.ts#L589) for `phase.isApplyExtrinsic` was found `true`. 

In Sidecar, when an event is in the `ApplyExtrinsic` phase, we expect that there is an extrinsic associated to it (mentioned also in a [SE](https://substrate.stackexchange.com/a/5438/234) answer). Then, we retrieve that extrinsic by accessing the index found in [phase.asApplyExtrinsic.toNumber](https://github.com/paritytech/substrate-api-sidecar/blob/cef2d10ead615b81c11a493310c84411fd45738f/src/services/blocks/BlocksService.ts#L590). 

In the block you indicated, if I check the contents of `phase` for the event `{method: 'MigrationAdvanced', section: 'multiBlockMigrations'...}` that you mentioned, I get `{"applyExtrinsic":2}` which means you relate this event with the extrinsic in index 2. I can see the same in [Subscan](https://shiden.subscan.io/block/7675808?tab=event) :

![mbm](https://github.com/user-attachments/assets/df5eea45-af2b-4798-8027-77fb8642096d)

and if I click on the indicated extrinsic [7675808-2](https://shiden.subscan.io/extrinsic/7675808-2) I am redirected to a page not found as you would expect.

Before adjusting Sidecar's code, I would like to determine if the issue lies within Sidecar's code or your migration logic. To clarify this, I have the following questions:
- Why is the phase set as `ApplyExtrinsic` when no extrinsic is attached to it? 
- And setting the phase as `ApplyExtrinsic` is necessary, why `applyExtrinsic` has the value of `2` when there is no extrinsic with index 2?

**Comment by ermalkaleci** [comment]
There's no issue with Shiden migration. We're using pallet-migrations from polkadot-sdk. While chain goes through migration, it applies only inherent extrinsic and then apply the migration. The extrinsic index will be incremented by 2 after inherent are applied so any event after will have extrinsic index 2 although there's no actual extrinsic triggering the migration. Migration is executed by the system itself. I don't know what will be the best solution to this but probably ignoring them or not link with an extrinsic may be a solution for now.

**Comment by ermalkaleci** [comment]
@ggwpez Hey Oliver I am tagging you since you worked on this pallet :)
I don't know if I should call this a feature or a bug :)
Since inherent events will update execution [phase](https://github.com/paritytech/polkadot-sdk/blob/edf79aa972bcf2e043e18065a9bb860ecdbd1a6e/substrate/frame/system/src/lib.rs#L2078) migration events are marked as `applyExtrinsic: 2`

**Comment by Imod7** [comment]
Apologies for the late reply. I will put a fix asap on this so we can correctly output the events related to `multiBlockMigrations`.

@ggwpez already shared this PR https://github.com/paritytech/polkadot-sdk/pull/3666 and when it gets merged I expect that these type of events will be set in phase `ApplyInherent` so in the future we would not have this issue anymore.

**Comment by ggwpez** [comment]
Yea sorry i think its a bug in FRAME, the phases are not quite right when a MBM is running.
