### ISSUE TITLE
Is there any way to distinguish between Inherents and Unsigned Transactions in json structure

### ISSUE THREAD

**Issue by zhenghq** [paritytech/substrate-api-sidecar#214]
I want to count signed transactions,unsigned transactions and inheritance separately, I have no idea which portion belong to inherent and which belong to unsigned transactions in extrinsics

**Comment by emostov** [comment]
Inherents and and unsigned transactions essentially are the same outside the runtime - the difference is with how they are processed internally. As far as I know there is not a generic solution to differentiate between inherents and unsigned transactions.

To differentiate between signed transactions and unsigned transactions/inherents in Sidecar responses, you should be able to look at the `info` field. If it is `{}`, then it is an unsigned transaction/inherent, otherwise it is a signed transaction.
