### ISSUE TITLE
Feature request: Add validator staking info endpoint

### ISSUE THREAD

**Issue by mariopino** [paritytech/substrate-api-sidecar#301]
**Proposed Change or Idea**

Thanks , this is a great and very needed tool!

Please, can you consider adding an endpoint with validator staking information:

Something equivalent to this JS api query:

```
const validatorAddresses = await api.query.session.validators()
const validatorStakingInfo = await Promise.all(validatorAddresses.map((authorityId) => api.derive.staking.account(authorityId)))
```

If same endpoint (or different) could include waiting validators that would be great!

**Alternatives**

[Are there alternative approaches or solutions that you’ve considered?]

**Additional Information**

[Add any other details about the feature request here.]

**Comment by emostov** [comment]
Hi - thanks for the proposal!

Is there specific information you are looking for from `api.derive.staking.account`? Is there a specific use case you have?

To outline Sidecar's current offerings that may help:

To get validator addresses you can query: `/pallets/session/storage/validators`.
Additionally `pallets/staking/progress` has the session validator set, among other info pertaining to era, session and election progress.

To retrieve precise payout information for any of those addresses you can query `/accounts/{validatorId}/staking-payout`.
And to get general staking info you can query `/accounts/{validatorId}/staking-info`.

If you have not already, I would recommend checking out the docs here: https://paritytech.github.io/substrate-api-sidecar/dist

CC @joepetrowski

**Comment by mariopino** [comment]
Hi, thanks  for the response! Our use case is to replace costly subscription based connections to Polkadot JS API by light queries to api sidecar when possible :-).

I'm interested in the following data for validators:

- Total, own and other exposures
- Identity
- Commission

With current version, is there a way to get that information?

PD: I get `Cannot GET /pallets/session/storage/validators` using `https://polkadot-api.w3f.community/pallets/session/storage/validators`.

**Comment by emostov** [comment]
@joepetrowski, @dvdplm is this still being considered?

**Comment by emostov** [comment]
Hi @mariopino ,

Are you still interested in this feature? If so can you elaborate further on why api-sidecar is the right place for this feature?

From what I can tell after re-reviewing the requirements you mention and the proposed use case it seems this would just be faster to do as direct RPC calls, like the example you give in your initial comments. Since api-sidecar aims to be stateless, it won't have any advantage on those RPC calls (unless I am missing something?); it would probably just end up slower.

**Comment by rjarasson-ledger** [comment]
Hi @emostov, @joepetrowski

We had the same needs for integrating Polkadot, and we implemented it in a custom branch that we are currently using.
Since this will be hard to maintain overtime, i was hoping to make some PRs months ago.

But due to performance issues on such endpoints gathering many info, and having non-generic features (and probably only polkadot-specific), we needed to consolidate more data at once (i am working on adding minRewarded / minNominated values for each validators, and maybe some of the computed values present done by the Polkadot.JS front-end here: https://github.com/polkadot-js/apps/blob/master/packages/page-staking/src/useSortedTargets.ts#L161-L216)

Hence, we chose the easy solution to add a cache (because we had no other solutions, and still have not), that leads to the feature being less likely to be mergeable into master.

You can find our solution here: https://github.com/Ledger-Coin-Integration-team/substrate-api-sidecar/tree/ledger-live

I would be glad to discuss some of the additions we made, absolutely needed for our integration to work well.

**Comment by emostov** [comment]
We are interested in adding the functionality you all have built, but as you touch on much of it is quite specific to the relay chain. (Although, maybe the identity endpoint itself could be considered part of our core functionality if you are interested in making a PR for that).

Given that, we would like to make sidecar more pluggable as outlined in #488. The staking routes you have in your fork could then extend the existing sidecar. It will likely take some time for that to play out though.

**Comment by TarikGul** [comment]
closing via: https://github.com/paritytech/substrate-api-sidecar/pull/1045
