### ISSUE TITLE
[meta] Performance tracking

### ISSUE THREAD

**Issue by emostov** [paritytech/substrate-api-sidecar#477]
This issue is a meta issue to track performance issues in api-sidecar related to high memory usage & slow response times, efforts to solve those issues, and general benchmarking efforts.

Analysis
- Benchmarking blocks endpoint. Currently in progress by @TarikGul 

Features
- Allow fetching of multiple blocks at once if it improves performance #460 

Bugs
- Issues with request timeouts and high memory usage #368

**Comment by TarikGul** [comment]
Important to note all performance benchmarking is tracked [here](https://github.com/TarikGul/Sidecar-Bench/tree/master/benchmarks/gcp-instance) for Sidecar. Specifically `/blocks` endpoint. This library should and could also be expanded for other endpoints. Benchmarking for Sidecar is currently tricky because of the way an archived chain works, and is synced. It could be a good idea to also look into some more effective ways to get all endpoints automated with benchmarks.

**Comment by TarikGul** [comment]
Closing in favor of: https://github.com/paritytech/substrate-api-sidecar/issues/1050
