### ISSUE TITLE
"transaction/fee-estimate" returns a value greater than later in the transaction

### ISSUE THREAD

**Issue by tryexceptend** [paritytech/substrate-api-sidecar#635]
Hi. I call "transaction/fee-estimate". This return 15600001600. However, in a transaction, the fee is equal to 3120000300. How do I calculate the fee? Or how to send all the amount from the account?

**Comment by tryexceptend** [comment]
substrate-api-sidecar: Version: 9.1.3
polkadot 0.9.8-3a10ee63c-x86_64-linux-gnu

**Comment by TarikGul** [comment]
Hey @tryexceptend , thanks for reporting the issue. I have a few questions:

1. To further confirm, the partial_fee of 15600001600, was received when you ran `/transactions/fee-estimate`, then shortly after you broadcasted your transaction to the node and received a partial_fee of 3120000300. Any chance you could send me the block height and extrinsic at which this took place so I can have a deeper look. (My main goal is to reproduce this myself in order to get a more accurate reading of what is happening with your partial_fee)

2. If you would like to calculate the fee manually on your own, we use a package called `@substrate/calc` in conjunction with sidecar. It resides inside of the sidecar repository here, and can be pulled down via npm. It's built in rust and compiles to wasm in order to make it usable in JS/TS. [README](https://github.com/paritytech/substrate-api-sidecar/blob/master/calc/README.md)

3. Can you elaborate what you mean by how to send all your amount from an account. As in you want to take all the tokens you have in an address and transfer it to another address, calculate the fee you will pay, then broadcast the transaction?

**Comment by tryexceptend** [comment]
1) Block 6435547. Tx 0x9b761dd3e10d05074b6d96b2a193bb636eebb756f3f6bc623e6f1665be1674ab. Using the SubstrateNetApi, I created a transaction. Called /transaction/fee-estimate. Returned fee = 15600001600. Then I deducted fee from the amount and send transaction. 
2) Thanks
3) I want to transfer the entire DOT amount from one account to another. Therefore, I first calculate the transfer commission and then create a transaction. In the transaction, the amount is equal to: balance - fee. It used to work correctly.

**Comment by TarikGul** [comment]
I made sure to test this locally first with a `balances.transferKeepAlive` when I ran the transaction against `/transaction/fee-estimate` I got the following:

```json
{
  "weight": "175696000", 
  "class": "Normal",
  "partialFee": "173054098"
}
```

Then when I queried the actual block at which the transaction happened I received: 

```
...
"info": {
        "weight": "175696000",
        "class": "Normal",
        "partialFee": "166049672"
      },
...
```

Here the difference seems to be very marginal at best. 

So when querying the block at which your transaction took place this is the result I am getting. 

```
      "hash": "0x9b761dd3e10d05074b6d96b2a193bb636eebb756f3f6bc623e6f1665be1674ab",
      "info": {
        "weight": "193987000",
        "class": "Normal",
        "partialFee": "156000015"
      },
```

How were you getting the fee of 3120000300?

**Comment by tryexceptend** [comment]
Sorry. I was wrong. You can close the topic

**Comment by TarikGul** [comment]
No worries, glad its resolved.
