### ISSUE TITLE
Support erc20 balance query and transfers

### ISSUE THREAD

**Issue by ianhe8x** [paritytech/substrate-api-sidecar#795]
**Proposed Change or Idea**

Substrate sidecar is a great project, most exchanges use it to integrate with substrate chains. 
One problem remains though, for projects deploy on a parachain's smart contract runtime. Sidecar doesn't support it yet. Neither other solutions work due to some compatibility issue with ethereum. (rosetta)

**Alternatives**

rosetta-ethereum

**Additional Information**

We plan to deploy our solution on Acala's EVM+. Depends on if this fit the direction of project, with some high level api design, I think we will be happy to contribute. Would like to hear your thoughts.

**Comment by TarikGul** [comment]
Hey @ianhe8x,

Yea support for smart contracts is something I think holds a lot of merit and something I think can fit within sidecars API. 

Some questions that come to mind:

1. Does polkadot-js have existing functionality to support this, or would we need to extend a PR there in order to have that support. [Polkadot-js contracts docs](https://polkadot.js.org/docs/api-contract/start/contract.read/). This is what I was able to find via the docs. 

2. In order to extend functionality towards many sets of smart contracts it might be wise to set the routes in the following design: `/contracts/ink`, `/contracts/evm` etc. What are your thoughts on that?

PR's are definitely most welcome, and ofcourse I would be here to help :) Glad to use this issue, and any subsequent PR, as a channel/discussion for design and implementation as well.

**Comment by TarikGul** [comment]
@ianhe8x Hey, is this something you are still interested in?

**Comment by guijunchen** [comment]
Is a general demand, can it support Support erc20/erc721 balance query and transfers?

**Comment by TarikGul** [comment]
Does it support ` erc20/erc721`, no. Can it, yes I am almost positive, but I will need to double check the functionality in polkadot.js.

Happy to make this part of our roadmap for sidecar.

**Comment by TarikGul** [comment]
This is a feature that will be focused in the Sidecar Rework where outside chains can add their own functionality. The purpose is to make it as extensible and easy enough for anyone to add your own logic. The focus of sidecar right now is to support core substrate pallets that are maintainable. At the moment we don't have the bandwidth to support third party pallets, and from our research there is no standardized way of connecting to an EVM smart contract across multiple parachain's. This makes maintenance and support very difficult across the board. 

For that reason we are closing the following issue.
