### ISSUE TITLE
Get extrinsic by hash

### ISSUE THREAD

**Issue by jrafael-simtlix** [paritytech/substrate-api-sidecar#910]
**Extrinsic hash query**

Every extrinsic has a hash, but there isn't a way to get it using its hash. Post /transaction returns the hash. So a Get /transaction/{hash} should return the transaction. 

**Alternatives**

[There is an extrinsic get by block and extrinsicIndex](https://paritytech.github.io/substrate-api-sidecar/dist/#operations-blocks-getExtrinsicByTimepoint). But it requires to know when a transaction is confirmed. If you need to check the state of a transaction and the block where is conformed is unknown, we can't do it.
 
**Additional Information**

There is a rpc that cover this feature that call [getTransactionByHash(hash: H256): EthTransaction](https://polkadot.js.org/docs/substrate/rpc/#gettransactionbyhashhash-h256-ethtransaction).

**Comment by TarikGul** [comment]
> There is a rpc that cover this feature that call [getTransactionByHash(hash: H256): EthTransaction](https://polkadot.js.org/docs/substrate/rpc/#gettransactionbyhashhash-h256-ethtransaction).

So the given RPC endpoint above is for ethereum and not substrate. 

> Every extrinsic has a hash, but there isn't a way to get it using its hash.

Transaction hashes are not unique in substrate as they are the result of the inputted data. What is unique though is a Timepoint, which is the the blockhash paired with the extrinsic index. 

> So a Get /transaction/{hash} should return the transaction.

Given the above since the transaction hash is not unique this would have to be targeted towards a specific block which would almost be identical to:  ["There is an extrinsic get by block and extrinsicIndex"](https://paritytech.github.io/substrate-api-sidecar/dist/#operations-blocks-getExtrinsicByTimepoint).

This requires you to poll the `/blocks` endpoint and search for your transaction after a transaction has been submitted to chain.
